command-to-be-run:
MongoDB:
  host: 'localhost'
  port: 27017
  database: 'testDB'
  collection: 'quests'
distanceToWalk: 500
EnchantAchievementLevel: 1
BlockRemoveAchievementCount: 50
BlockPlaceAchievementCount: 50
#Place holders:
#%achivement%
#%player%
Achivement-message: 'Congratulations %player%, you just finished the %achivement% achivement'