name: QuestsTest
version: '${project.version}'
main: com.github.ukraine1449.queststest.QuestsTest
authors: [ Ukraine1449 ]
commands:
  quests:
    description: see all your quests
    permission: QuestTest.quests
    permission-message: You need to have the QuestTest.quests permission to use this command or be OP